DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS notes;

CREATE TABLE user (
ID INTEGER PRIMARY KEY AUTOINCREMENT,
name TEXT NOT NULL,
email TEXT UNIQUE NOT NULL,
password TEXT NOT NULL
);


CREATE TABLE notes (
ID INTEGER PRIMARY KEY AUTOINCREMENT,
workout TEXT NOT NULL,
exercise TEXT NOT NULL,
weight FLOAT NOT NULL
)